package com.data_object.pr_objects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class data_bus_dim implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public data_bus_dim() {
    }




}