package com.data_object.pr_objects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class pub_cns_combined_flattened_bre implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public pub_cns_combined_flattened_bre() {
    }




}